<?php

class MainController extends ModuleAdminController

{
    public function actionAdmin()
    {
//        parent::actionAdmin(); // TODO: Change the autogenerated stub

        return 'Hello';
    }
}